//get category list for job
export const GET_JOB_CATEGORY_LIST_INIT = "GET_JOB_CATEGORY_LIST_INIT";
export const GET_JOB_CATEGORY_LIST_SUCCESS = "GET_JOB_CATEGORY_LIST_SUCCESS";
export const GET_JOB_CATEGORY_LIST_FAILED = "GET_JOB_CATEGORY_LIST_FAILED";

//get subcategory list fir job
export const GET_JOB_SUB_CATEGORY_LIST_INIT = "GET_JOB_SUB_CATEGORY_LIST_INIT";
export const GET_JOB_SUB_CATEGORY_LIST_SUCCESS = "GET_JOB_SUB_CATEGORY_LIST_SUCCESS";
export const GET_JOB_SUB_CATEGORY_LIST_FAILED = "GET_JOB_CATEGORY_LIST_FAILED";

//SAVE JOB DETAILS
export const SAVE_JOB_DETAIL_INIT = "SAVE_JOB_DETAIL_INIT";
export const SAVE_JOB_DETAIL_SUCCESS = "SAVE_JOB_DETAIL_SUCCESS";
export const SAVE_JOB_DETAIL_FAILED = "SAVE_JOB_DETAIL_FAILED";

// save 
export const SAVE_JOB_PREFERENCES_INIT = "SAVE_JOB_PREFERENCES_INIT";
export const SAVE_JOB_PREFERENCES_SUCCESS = "SAVE_JOB_PREFERENCES_SUCCESS";
export const SAVE_JOB_PREFERENCES_FAILED = "SAVE_JOB_PREFERENCES_FAILED";

