//job browse on the seeker dashboard
export const GET_JOB_BROWSE_LIST_INIT = "GET_JOB_BROWSE_LIST_INIT";
export const GET_JOB_BROWSE_LIST_SUCCESS = "GET_JOB_BROWSE_LIST_SUCCESS";
export const GET_JOB_BROWSE_LIST_FAILED = "GET_JOB_BROWSE_LIST_FAILED";

// get job types
export const GET_JOB_TYPE_LIST_INIT = "GET_JOB_TYPE_LIST_INIT";
export const GET_JOB_TYPE_LIST_SUCCESS = "GET_JOB_TYPE_LIST_SUCCESS";
export const GET_JOB_TYPE_LIST_FAILED = "GET_JOB_TYPE_LIST_FAILED";

// get particular job details
export const GET_JOB_DETAIL_INIT = "GET_JOB_DETAIL_INIT";
export const GET_JOB_DETAIL_SUCCESS = "GET_JOB_DETAIL_SUCCESS";
export const GET_JOB_DETAIL_FAILED = "GET_JOB_DETAIL_FAILED";

// post apply jobs
export const POST_APPLY_JOB_INIT = "POST_APPLY_JOB_INIT";
export const POST_APPLY_JOB_SUCCESS = "POST_APPLY_JOB_SUCCESS";
export const POST_APPLY_JOB_FAILED = "POST_APPLY_JOB_FAILED";

// active and inactive the posted jobs
export const POST_POSTED_JOB_STATUS_INIT = "POST_POSTED_JOB_STATUS_INIT";
export const POST_POSTED_JOB_STATUS_SUCCESS = "POST_POSTED_JOB_STATUS_SUCCESS";
export const POST_POSTED_JOB_STATUS_FAILED = "POST_POSTED_JOB_STATUS_FAILED";

// remove the posted job
export const REMOVE_JOBS_INIT = "REMOVE_JOBS_INIT";
export const REMOVE_JOBS_SUCCESS = "REMOVE_JOBS_SUCCESS";
export const REMOVE_JOBS_FAILED = "REMOVE_JOBS_FAILED";


// get list of applied job
export const GET_APPLIED_JOB_INIT = "GET_APPLLIED_JOB_INIT";
export const GET_APPLIED_JOB_SUCCESS = "GET_APPLLIED_JOB_SUCCESS";
export const GET_APPLIED_JOB_FAILED = "GET_APPLIED_JOB_FAILED";

// get list of visaType
export const GET_LIST_VISA_TYPE_INIT = "GET_LIST_VISA_TYPE_INIT";
export const GET_LIST_VISA_TYPE_SUCCESS = "GET_LIST_VISA_TYPE_SUCCESS";
export const GET_LIST_VISA_TYPE_FAILED = "GET_LIST_VISA_TYPE_FAILED";

// get education list
export const GET_EDUCATION_LIST_INIT = "GET_EDUCATION_LIST_INIT";
export const GET_EDUCATION_LIST_SUCCESS = "GET_EDUCATION_LIST_SUCCESS";
export const GET_EDUCATION_LIST_FAILED = "GET_EDUCATION_LIST_FAILED";

// get skills list
export const GET_SKILLS_LIST_INIT = "GET_SKILLS_LIST_INIT";
export const GET_SKILLS_LIST_SUCCESS = "GET_SKILLS_LIST_SUCCESS";
export const GET_SKILLS_LIST_FAILED = "GET_SKILLS_LIST_FAILED";

//get applied candidate list
export const GET_CANDIDATE_LIST_INIT = "GET_CANDIDATE_LIST_INIT";
export const GET_CANDIDATE_LIST_SUCCESS = "GET_CANDIDATE_LIST_SUCCESS";
export const GET_CANDIDATE_LIST_FAILED = "GET_CANDIDATE_LIST_FAILED";

// get the candidate details
export const GET_CANDIDATE_DETAIL_INIT = "GET_CANDIDATE_DETAIL_INIT";
export const GET_CANDIDATE_DETAIL_SUCCESS = "GET_CANDIDATE_DETAIL_SUCCESS";
export const GET_CANDIDATE_DETAIL_FAILED = "GET_CANDIDATE_DETAIL_FAILED";

//candidate shortlist or reject

export const CANDIDATE_SHORTLIST_INIT = "CANDIDATE_SHORTLIST_INIT";
export const CANDIDATE_SHORTLIST_SUCCESS = "CANDIDATE_SHORTLIST_SUCCESS";
export const CANDIDATE_SHORTLIST_FAILED = "CANDIDATE_SHORTLIST_FAILED";

// schedule interview 

export const SCHEDULE_INTERVIEW_INIT = "SCHEDULE_INTERVIEW_INITT";
export const SCHEDULE_INTERVIEW_SUCCESS = "SCHEDULE_INTERVIEW_SUCCESS";
export const SCHEDULE_INTERVIEW_FAILED = "SCHEDULE_INTERVIEW_FAILED";

// posted a new jobs
export const POSTED_NEW_JOB_INIT = "POSTED_NEW_JOB_INIT ";
export const POSTED_NEW_JOB_SUCCESS = "POSTED_NEW_JOB_SUCCESS";
export const POSTED_NEW_JOB_FAILED = "POSTED_NEW_JOB_FAILED";

// edited the new jobs
export const EDIT_JOBS_INIT = "EDIT_JOBS_INIT ";
export const EDIT_JOBS_SUCCESS = "EDIT_JOBS_SUCCESS";
export const EDIT_JOBS_FAILED = "EDIT_JOBS_FAILED";

// uploaded documents

export const UPLOADED_DOCUMENT_INIT = "UPLOADED_DOCUMENT_INIT";
export const UPLOADED_DOCUMENT_SUCCESS = "UPLOADED_DOCUMENT_SUCCESS";
export const UPLOADED_DOCUMENT_FAILED = "UPLOADED_DOCUMENT_FAILED";

// 
export const BASIC_DETAIL_JOBPOSTER_INIT= "BASIC_DETAIL_JOBPOSTER_INIT";
export const BASIC_DETAIL_JOBPOSTER_SUCCESS = "BASIC_DETAIL_JOBPOSTER_SUCCESS";
export const BASIC_DETAIL_JOBPOSTER_FAILED = "BASIC_DETAIL_JOBPOSTER_FAILED";

// add the favorite
export const POST_FAVORITE_INIT = "POST_FAVORITE_INIT";
export const POST_FAVORITE_SUCCESS = "POST_FAVORITE_SUCCESS";
export const POST_FAVORITE_FAILED = "POST_FAVORITE_FAILED";

// get the favorite jobs
export const GET_FAVORITE_INIT = "GET_FAVORITE_INIT";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAILED = "GET_FAVORITE_FAILED";

//subscription
export const GET_SUBSCRIPTION_PLAN_INIT = 'GET_SUBSCRIPTION_PLAN_INIT';
export const GET_SUBSCRIPTION_PLAN_SUCCESS = 'GET_SUBSCRIPTION_PLAN_SUCCESS';
export const GET_SUBSCRIPTION_PLAN_FAILED = 'GET_SUBSCRIPTION_PLAN_FAILED';


